### ISSUE TITLE
Using other people's signatures/identity for your commits

### ISSUE THREAD

**Issue by nine7nine** [King-Kernel/KingKernel-marlin-old#1]
I did not signoff on or write/make these commits;

EXNS/PIE: Adaptive Battery deps
5c33c92312d3101e7566fa74fa71dd123ec42a13

EXNS/PIE: Adaptive Battery deps fixed commit
5e648be3e9329d1f56b68adf97aa55539e866d24

You have absolutely no business using other people's identities / signatures on your own commits.

STOP DOING THIS AND REMOVE THIS GARBAGE.

**Comment by nine7nine** [comment]
We've been over this and you know it ~ Do you think I cannot see what repositories that I've "supposedly" contributed too????

Use your brain kingbri, you told months ago not to do this...

I demand that you remove these commits and stop using my signature.

redo your your dirpy crappy commits using your own signature and leave me out of it!

**Comment by kingbri1** [comment]
We didn't talk about it per se, you just kept berating me with insults, but I am fixing the commits as I post this, I will close this issue once fixed

**Comment by nine7nine** [comment]
there's nothing to discuss, this kind of crap should've never been done in the first place - and certainly not months later; after you were told not to use my identity /signature in YOUR crappy commits....

and frankly, after all of the manipulative crap u pulled with myself and other people; i have absolute distain towards you and ZERO respect...

if you thought there was anything to discuss ''per se'', you were dead wrong. use your own signoff, not mine.

**Comment by kingbri1** [comment]
Everything fixed, issue closed

**Comment by nine7nine** [comment]
Good, hopefully I never hear from you again.
